---
- name: Download Consul
  sudo: yes
  shell: curl -o {{ consul_install_dir }}/{{ consul_archive }}.zip {{ consul_url }}

- name: Extract Consul
  sudo: yes
  unarchive: copy=no src={{ consul_install_dir }}/{{ consul_archive }}.zip dest={{ consul_install_dir }}

- name: Remove downloaded consul_archive
  sudo: yes
  shell: "rm -f {{ consul_install_dir }}/{{ consul_archive }}.zip"
