---

- name: Install dependencies required to deploy things with Python
  sudo: yes
  apt: pkg={{ item }} state=latest
  tags: [packages]
  with_items:
    - build-essential
    - libsqlite3-dev
    - sqlite3 # for the command line client
    - libxml2-dev
    - bzip2
    - libbz2-dev
    - libssl-dev
    - redis-server
    - libffi-dev

- name: Install packages required for Sphinx
  sudo: yes
  pip: name={{ item }}
  with_items:
    - sphinx==1.4.8
    - recommonmark
    - sphinx-autobuild
    - nbsphinx
    - sphinx_rtd_theme
    - jupyter_sphinx_theme
    - recommonmark
