---

- name: Install dependencies required to deploy things with Python
  sudo: yes
  apt: pkg={{ item }} state=latest
  tags: [packages]
  with_items:
    - build-essential
    - libsqlite3-dev
    - sqlite3 # for the command line client
    - libxml2-dev
    - bzip2
    - libbz2-dev
    - libssl-dev
    - redis-server

- name: Install packages required for Sphinx
  pip: name={{ item }} virtualenv="~/snowplow-python-3.3-tracker-environment"
  with_items: 
    - sphinx
    - sphinx-autobuild
    - sphinxcontrib-spelling
    - nbsphinx
    - sphinx_rtd_theme
    - jupyter_sphinx_theme
    - recommonmark
